In [1]:
import torch 
import torch.nn as nn

In [17]:
input = torch.tensor([.3, -.1, .5, 1, 3, 8], dtype=torch.float32, device='cuda')

In [11]:
m = nn.ReLU6()
m(input)

tensor([0.3000, 0.0000, 0.5000, 1.0000, 3.0000, 6.0000], device='cuda:0')

In [22]:
input

tensor([ 0.3000, -0.1000,  0.5000,  1.0000,  3.0000,  8.0000], device='cuda:0')

In [25]:
a = torch.max(input)

In [29]:
a

tensor(8., device='cuda:0')

In [34]:
torch.min(torch.max(input), torch.tensor(6))

tensor(6., device='cuda:0')

In [39]:
def ReLU6(x):
    return torch.minimum(torch.maximum(input, torch.tensor(0)), torch.tensor(6))

In [40]:
ReLU6(input)

tensor([0.3000, 0.0000, 0.5000, 1.0000, 3.0000, 6.0000], device='cuda:0')